name: Bug report
description: Report a bug or unexpected behavior in NebulaDesk Core
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Thanks for helping improve NebulaDesk Core! Please provide details below.

  - type: input
    id: summary
    attributes:
      label: Brief summary
      description: "What happened in one or two sentences?"
      placeholder: "Example: Notes widget doesn't unlock after entering the passphrase"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "List clear steps that trigger the bug."
      value: |
        1.
        2.
        3.
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: "What actually happened?"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - Core (PWA / service worker)
        - Storage / Encryption
        - Widgets
        - Docs
        - Security / CSP
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version or commit
      placeholder: "v0.1.0 or 7a1b2c3"

  - type: textarea
    id: logs
    attributes:
      label: Console errors or logs
      description: "Paste relevant console output or screenshots."
      render: bash

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues before submitting.
          required: true
        - label: I’m using the latest version.
          required: false
