name: Feature request
description: Suggest a new feature, widget, or improvement for NebulaDesk Core
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        Describe the feature you’d like to see and why it would be useful.

  - type: input
    id: summary
    attributes:
      label: Feature summary
      placeholder: "Example: Add a light/dark theme toggle"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: "What problem or limitation does this address?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "How should it work? Be specific."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / workarounds
      description: "Other approaches you considered."

  - type: dropdown
    id: area
    attributes:
      label: Feature area
      options:
        - Core (PWA / app shell)
        - Storage / Encryption
        - Widgets
        - UI / UX
        - Security / CSP
        - Docs
        - Other
    validations:
      required: true

  - type: input
    id: priority
    attributes:
      label: Priority (optional)
      placeholder: "Low / Medium / High"

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues to avoid duplicates.
          required: true
        - label: I’m willing to help design or test this feature.
          required: false
